### PR TITLE
update peer deps

### PR DESCRIPTION
**Pull request by createthis**
#24

### CODE REVIEW

**Comment by rkotze** [comment]
Hello thanks for the updates. I tried running should 12 and 13 for my unit tests and they break.
Not sure why at the moment, this will need further investigation.

Are you having any issues with should v13 and should enzyme in your project?

**Comment by createthis** [comment]
I'm not and all of my unit tests pass.

```bash
  308 passing (1s)
```

oh, nvm, I see it installed should 11. one moment.

**Comment by rkotze** [comment]
Okay good. I'll look into should-enzyme tests soon, to figure out what is breaking.

**Comment by createthis** [comment]
Yeah, I see the failures now. Hrm. I may take a look at this later, though I'm not really too familiar with the internals of should. So far I've just used `present()` from this library and that seems to work with 13. Looks like a few other things are broken though.

**Pull request merged**
